kind: pipeline
type: docker
name: cicd

steps:
  - name: test
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - docker-compose -f docker-compose.test.yml build --no-cache --force-rm
      - docker-compose -f docker-compose.test.yml up -d
    when:
      branch:
        - develop
      event:
        - push
        - pull_request
  - name: cleanup
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - docker image prune -a -f
    when:
      status:
        - success
        - failure

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock